# ============================================================================
# NETAPP ONTAP CONFIGURATION FILE
# ============================================================================
# Configuration file for NetApp ONTAP automation scripts
# Version: 1.0.0
# ============================================================================

# CLUSTER CONNECTION SETTINGS
cluster:
  host: cluster1.demo.netapp.com            
  username: admin
  password: "Netapp1!"

# STORAGE VIRTUAL MACHINE (SVM) SETTINGS
svm:
  name: svm_1_cluster


# ADAPTIVE QOS POLICY SETTINGS
aqos_policy:
  name: NAS1200_SVMv2-XXXXXX-RHOSO_COR_NAS01-NAS
  vserver: svm_1_cluster
  expected_iops: 1200              # IOPS/TB esperados
  peak_iops: 3600                  # IOPS/TB pico
  expected_iops_allocation: allocated_space   # allocated_space o used_space
  peak_iops_allocation: allocated_space       # allocated_space o used_space
  absolute_min_iops: 1200          # IOPS mínimos absolutos
  block_size: ANY                  # Tamaño de bloque (ANY, 4k, 8k, etc.)
